from module import*
shop1=Shop("атб","повседневный")
shop1.describe_shop()
shop1.open_shop()
shop2=Shop("эпицентр","строительный")
shop2.describe_shop()
n=int(input("задайте количество товара --> "))
shop1.set_number_of_units(n)
m=int(input("количество товара после завоза--> "))
shop1.increment_number_of_units(m)
store_discount=Discount("варус","повседневный")
store_discount.get_discounts_products()
all_store=Shop("диалог","конфетный")
all_store.describe_shop()
